### ISSUE TITLE
the report button does not bring me the information

### ISSUE THREAD

**Issue by Nikitore** [cbradburne/Pan-Tilt-Mount-App#1]
hello thank you for designing the application. I am trying to use it, I connect the joystick and the port of the hc-05 module but when I press the report button it does not bring me the information as in the video. What can it be?
![Sin título](https://user-images.githubusercontent.com/99223586/155137604-5d3b89b7-e5d7-4e11-8735-c580af978a46.png)

**Comment by cbradburne** [comment]
Hi, thanks for downloading any trying out the app.

Does everything else work ok? Is it moving the pan / tilt mount?

**Comment by Nikitore** [comment]
Hi! It is not working. Send information through the serial port and the motors move back and forth. But they do not complete the command correctly. Attach a video where you can see the problem. Also when I use your application with the xbox joystick through the usb port the same thing happens. The motors loop back and forth but do not move, this causes my battery to drain very quickly. What do you think it could be? Are the motor cables twisted?  Thanks! 

![tilt motor](https://user-images.githubusercontent.com/99223586/159504151-6af30527-1af8-41b6-9765-e9a4e13bf890.jpeg)
![wired connection](https://user-images.githubusercontent.com/99223586/159504157-ab78a165-7790-40de-8333-7c08a927837a.jpeg)

https://user-images.githubusercontent.com/99223586/159502067-d90f3f6c-e082-4624-bb5e-c7ff5b42b1c7.mp4

**Comment by cbradburne** [comment]
That's a classic "stepper motors wired wrong" sound.

Unplug the motor connection to your PCB, and continuity check the left 2 wires (Red & Blue) and the right 2 wires (Green & Black). They should both show either a short, or very low resistance.

If they don't, you'll need to swap the pins around so they do. Then if the motor still judders, do what's written next.

If they do, one of the pairs will be the wrong polarity, just swap red blue around.

Let me know how that goes.

**Comment by cbradburne** [comment]
...edited after re reading your comment.

You mention the same thing happens when using the XBOX controller and my app via USB. That hopefully means my app is working fine. Just need to sort your stepper wiring out.

Regarding the HC-05, have you successfully paired the HC-05 with your PC?
If not, here's a bit of a "how to" [LINK](https://www.instructables.com/Arduino-AND-Bluetooth-HC-05-Connecting-easily/)

**Comment by Nikitore** [comment]
The HC-05 module is now properly connected to the computer. And I think the App is working correctly. It is most likely that in my case the problem is wiring, as soon as I find out I will tell you.  Thank you very much for that answer I will try it today.

**Comment by cbradburne** [comment]
Hi. I hope you'll post back to report on how it's going. Success or not.

**Comment by Nikitore** [comment]
Hi, I connected the cables correctly and the tilt motor worked perfectly. I was able to make it work with your app and move it through an Xbox joystick. The other two motors I changed the cables but they still don't work. I'll keep testing and let you know. 😊

**Comment by cbradburne** [comment]
ok great!

I know it can be fun trying to get the polarities correct for stepper motors. If the wires on the left are "ringing out" try swiping those 2 cables around.

Basically, there are 2 coils, A and B. Each coil has a +ve and -ve side. By continuity testing you can find coil A and coil B, but the polarity of the coils may still not match. Test for continuity and put 1 pair of wires on the left side of the plug and the other 2 on the right, but if your motor is still juddering, swap the left 2 wires around to swap the polarity of one side, and it should be fine.

I hope that makes sense.

**Comment by Nikitore** [comment]
Thanks man! Make sense! Right now pan and tilt motor are working good! 😊 It is just one motor left.

**Comment by Nikitore** [comment]
I found that one of the TMC 2208 drivers is burned out, that's why the third motor was not working. Now when I press the report button I get the following screen. 
![app slider](https://user-images.githubusercontent.com/99223586/159801985-890db5ac-d020-4f5c-ab05-0517aa837127.png)

**Comment by cbradburne** [comment]
Ah ok. Looks like it's looking in my user folder "col" rather than yours.
I'll have a think about how to fix that.

Thanks for the screenshot. Glad you got things working, sorry a stepper has burned out.

**Comment by Nikitore** [comment]
Thanks for all your help, I really appreciate it. It's a pity about the driver, I burned it by connecting the arduino to the PCB wrong the first time. On that occasion I burned the Arduino and the HC-05 module. I learned a lot with this project

**Comment by cbradburne** [comment]
I've uploaded a different version of the app, compiled with "pyinstaller" rather than "cx_freeze", I hope this has compiled it differently.

You'll find it in the new "Experimental" folder. [LINK](https://github.com/cbradburne/Pan-Tilt-Mount-App/tree/main/Experimental)
Please give it a try and let me know how it goes.

**Comment by Nikitore** [comment]
I'll try it and let you know how it went.

**Comment by Nikitore** [comment]
Is working! Now I am going to entertain myself learning all the commands! Thanks!
![image](https://user-images.githubusercontent.com/99223586/159813117-aa630859-a18b-485d-ba6a-975dc832b13a.png)

**Comment by cbradburne** [comment]
AMAZING!

Thank you for your patience. I hope you do have fun with it.
